apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search-ms
  labels:
    app: elastic-search-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-search-ms
  template:
    metadata:
      labels:
        app: elastic-search-ms
    spec:
      containers:
        - name: elastic-search-ms
          image: islamahmad/eaproj-elastic-searchms:1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "islamahmad/eaproj-elastic-searchms:1.0.9"

            - name: SERVER_PORT
              value: "8080"

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-search-ms
                  key: REDIS_PASSWORD

          envFrom:
            - configMapRef:
                name: elastic-search-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global
